name: Bug Report
description: 报告一个 bug 来帮助我们改进
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感谢你花时间填写这个 bug 报告！

  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么？
      description: 详细描述遇到的问题
      placeholder: 告诉我们发生了什么！
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期望的行为
      description: 描述你期望发生的情况
      placeholder: 你期望发生什么？
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 重现步骤
      description: 详细的重现步骤
      placeholder: |
        1. 运行命令 '...'
        2. 点击 '....'
        3. 滚动到 '....'
        4. 看到错误
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: 操作系统
      description: 你在哪个操作系统上遇到了这个问题？
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (其他发行版)
        - 其他
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: TimeTracker 版本
      description: 你使用的 TimeTracker 版本是什么？
      placeholder: "例如：0.2.0"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 相关日志
      description: 请复制并粘贴任何相关的日志输出。这将自动格式化为代码，所以不需要反引号。
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: 检查清单
      description: 在提交之前，请确认以下事项
      options:
        - label: 我已经搜索了现有的 issues，没有找到重复的问题
          required: true
        - label: 我已经阅读了文档和 README
          required: true
        - label: 我提供了足够的信息来重现这个问题
          required: true