version: '3.8'

services:
  timetracker:
    build: .
    container_name: timetracker
    restart: unless-stopped
    volumes:
      - timetracker_data:/home/timetracker/.timetracker
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - RUST_LOG=info
    network_mode: host
    # 需要访问 X11 显示服务器
    privileged: true
    
  # 可选：用于开发的服务
  timetracker-dev:
    build:
      context: .
      target: builder
    container_name: timetracker-dev
    volumes:
      - .:/usr/src/app
      - timetracker_dev_cache:/usr/src/app/target
    working_dir: /usr/src/app
    command: cargo run
    profiles:
      - dev

volumes:
  timetracker_data:
    driver: local
  timetracker_dev_cache:
    driver: local